sonar.projectKey=XasCode_terrafile-backend-lib
sonar.organization=xascode
sonar.host.url=https://sonarcloud.io

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=terrafile-backend-lib
sonar.projectVersion=1.0

# Paths are relative to the sonar-project.properties file.
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.spec.ts
sonar.exclusions=node_modules/**,coverage/**,dist/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# LCOV report path
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
